//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace English_Learning.RESX {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("English_Learning.RESX.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на App Activity End Time.
        /// </summary>
        public static string AppActivityEnd {
            get {
                return ResourceManager.GetString("AppActivityEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на App Activity Start Time.
        /// </summary>
        public static string AppActivityStart {
            get {
                return ResourceManager.GetString("AppActivityStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cancel.
        /// </summary>
        public static string CancelButton {
            get {
                return ResourceManager.GetString("CancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Pimsleur recommended repeating words 11 times. His conclusions are that repetitions are needed after 30 minutes, in the morning of the next day; after three days; later: a week, a month, three months, six months and a year. Frequent encounters with unfamiliar phrases in English are necessary to create and strengthen new neural connections.
        ///
        ///Leitner method. Words are divided into groups with repetition intervals and repeated with a certain frequency. Once a day, every other day, once a week, once every two [остаток строки не уместился]&quot;;.
        /// </summary>
        public static string DetailAboutMethodDescription {
            get {
                return ResourceManager.GetString("DetailAboutMethodDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на About methods.
        /// </summary>
        public static string DetailAboutMethods {
            get {
                return ResourceManager.GetString("DetailAboutMethods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Back.
        /// </summary>
        public static string DetailAboutMethodsBackButton {
            get {
                return ResourceManager.GetString("DetailAboutMethodsBackButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на About methods.
        /// </summary>
        public static string DetailAboutMethodsTitle {
            get {
                return ResourceManager.GetString("DetailAboutMethodsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Archive.
        /// </summary>
        public static string DetailArchive {
            get {
                return ResourceManager.GetString("DetailArchive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Delete.
        /// </summary>
        public static string DetailDelete {
            get {
                return ResourceManager.GetString("DetailDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Method.
        /// </summary>
        public static string DetailMethod {
            get {
                return ResourceManager.GetString("DetailMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Word.
        /// </summary>
        public static string DetailPageTitle {
            get {
                return ResourceManager.GetString("DetailPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Save.
        /// </summary>
        public static string DetailSave {
            get {
                return ResourceManager.GetString("DetailSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Translation.
        /// </summary>
        public static string DetailTranslationButton {
            get {
                return ResourceManager.GetString("DetailTranslationButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Word details.
        /// </summary>
        public static string DetailWord {
            get {
                return ResourceManager.GetString("DetailWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Home.
        /// </summary>
        public static string HomePageTitile {
            get {
                return ResourceManager.GetString("HomePageTitile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;Description&gt;.
        /// </summary>
        public static string LeitnerMethodDescription {
            get {
                return ResourceManager.GetString("LeitnerMethodDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The Leitner&apos;s Method.
        /// </summary>
        public static string LeitnerMethodTitle {
            get {
                return ResourceManager.GetString("LeitnerMethodTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;Description&gt;.
        /// </summary>
        public static string PimslerMethodDescription {
            get {
                return ResourceManager.GetString("PimslerMethodDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The Pimsleur&apos;s Method.
        /// </summary>
        public static string PimslerMethodTitle {
            get {
                return ResourceManager.GetString("PimslerMethodTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Only Push.
        /// </summary>
        public static string PreferencesNotification {
            get {
                return ResourceManager.GetString("PreferencesNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ok.
        /// </summary>
        public static string WelcomeButton {
            get {
                return ResourceManager.GetString("WelcomeButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Welcome! The first time you start, you need to configure the application..
        /// </summary>
        public static string WelcomeText {
            get {
                return ResourceManager.GetString("WelcomeText", resourceCulture);
            }
        }
    }
}
